version: '3'
name: musin
services:
  api:
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile
    env_file:
      - ./environment/development.env
      - ./environment/secrets.env
    command: /bin/bash -c
      "source /nest/build/bin/nest_vars.sh
      && export NEST_MODULE_PATH=/nest/build/lib/nest:$NEST_MODULE_PATH
      && export SLI_PATH=/nest/build/share/nest/sli:$SLI_PATH
      && chmod +x ./docker/run_gunicorn.sh
      && ./docker/run_gunicorn.sh"
    # command: /bin/bash -c
    #   "source /nest/build/bin/nest_vars.sh
    #   && export NEST_MODULE_PATH=/nest/build/lib/nest:$NEST_MODULE_PATH
    #   && export SLI_PATH=/nest/build/share/nest/sli:$SLI_PATH
    #   && gunicorn --bind 0.0.0.0:5000 api:api"
    volumes:
      - .:/app
    ports:
      - "5555:5000"
    links:
      - mysql
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/init/init.sql:/data/mysql/init.sql
    restart: unless-stopped
    ports:
      - "3306:3306"
    env_file:
      - ./environment/development.env
      - ./environment/secrets.env
    command: --init-file /data/mysql/init.sql
  
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    ports:
      - "8888:80"
    env_file:
      - ./environment/phpmyadmin.env
      - ./environment/secrets.env
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

volumes:
  mysql-data:
    driver: local
