version: '3'
name: musin
services:
  web:
    build: .
    environment:
      - FLASK_APP=manage.py
      - FLASK_DEBUG=1
      - PYTHONFAULTHANDLER=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    command: /bin/bash -c
      "source /nest/build/bin/nest_vars.sh
      && export NEST_MODULE_PATH=/nest/build/lib/nest:$NEST_MODULE_PATH
      && export SLI_PATH=/nest/build/share/nest/sli:$SLI_PATH
      && ls -la
      && chmod +x run_gunicorn.sh
      && ./run_gunicorn.sh"
    # command: /bin/bash -c
    #   "source /nest/build/bin/nest_vars.sh
    #   && export NEST_MODULE_PATH=/nest/build/lib/nest:$NEST_MODULE_PATH
    #   && export SLI_PATH=/nest/build/share/nest/sli:$SLI_PATH
    #   && gunicorn --bind 0.0.0.0:5000 api:api"
    volumes:
      - .:/app
    ports:
      - "5555:5000"
    links:
      - db
  # db:
  #   image: mysql:latest
  #   environment:
  #     MYSQL_DATABASE_DB: sensorycerebellum
  #     MYSQL_DATABASE_USER: root
  #     MYSQL_DATABASE_PASSWORD: CerebSens01!
  #     MYSQL_DATABASE_CHARSET: utf8mb4
  #   ports:
  #     - "3306:3306"
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=musin
      - POSTGRES_PASSWORD=musin
      - POSTGRES_DB=musin_db
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - web

volumes:
  postgres_data:
